# Generated by Django 5.2.4 on 2026-04-18 11:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/media/employee_images/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='joining_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_no',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^[0-9]{10}$')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
