# Generated by Django 6.0.4 on 2026-05-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('address', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=50)),
                ('financial_year_start', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Company Settings',
                'verbose_name_plural': 'Company Settings',
            },
        ),
        migrations.CreateModel(
            name='LeavePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('SICK', 'Sick Leave'), ('ANNUAL', 'Annual Leave')], max_length=20, unique=True)),
                ('days_allowed', models.IntegerField(default=12)),
                ('carry_forward', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Leave Policy',
                'verbose_name_plural': 'Leave Policies',
            },
        ),
        migrations.CreateModel(
            name='WorkingDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3, unique=True)),
                ('is_working', models.BooleanField(default=True)),
                ('work_start', models.TimeField(default='09:00')),
                ('work_end', models.TimeField(default='18:00')),
            ],
            options={
                'verbose_name': 'Working Day',
                'verbose_name_plural': 'Working Days',
                'ordering': [models.Case(models.When(day='MON', then=0), models.When(day='TUE', then=1), models.When(day='WED', then=2), models.When(day='THU', then=3), models.When(day='FRI', then=4), models.When(day='SAT', then=5), models.When(day='SUN', then=6), default=7, output_field=models.IntegerField())],
            },
        ),
    ]
