# Generated by Django 6.0.4 on 2026-04-14 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_warehouse_product_brand_stocktransaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorystocks',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
            preserve_default=False,
        ),
    ]
