# Generated by Django 6.0.4 on 2026-05-12 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('segment', models.CharField(choices=[('hardware', 'Hardware'), ('logistics', 'Logistics'), ('software', 'Software'), ('raw_material', 'Raw Material')], max_length=50)),
                ('performance', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average')], default='good', max_length=20)),
                ('score', models.IntegerField(default=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('estimated_delivery', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('in_transit', 'In Transit'), ('delayed', 'Delayed'), ('delivered', 'Delivered')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procurement.supplier')),
            ],
        ),
    ]
