# Generated by Django 5.2.4 on 2026-04-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='OrederItem',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='Customer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='ststus',
        ),
        migrations.AlterField(
            model_name='customer',
            name='full_name',
            field=models.CharField(max_length=50),
        ),
    ]
