# Generated by Django 5.2.4 on 2026-04-18 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_rename_orderitem_orederitem_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrederItem',
            new_name='OrderItem',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Customer',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='ststus',
            new_name='status',
        ),
    ]
